/* -----------------------------------------------------------------------------
 * embind.cxx
 *
 * SWIG language module that emits Emscripten Embind C++ bindings
 * (EMSCRIPTEN_BINDINGS(...) blocks).  Intended to leverage SWIG's parsing,
 * %ignore/%rename, and feature filtering for large APIs (e.g. CasADi) without
 * writing the Embind boilerplate by hand.
 *
 * Status: experimental, free functions + classes (methods, default ctor) only.
 * ----------------------------------------------------------------------------- */

#include "swigmod.h"

static File   *f_out = 0;
static String *f_body = 0;
static String *f_header = 0;
static String *current_class_cname = 0;
static String *current_enum_cname = 0;
static Hash   *ctor_arities_seen = 0;   /* set<int> per class */

class EMBIND : public Language {
public:
  EMBIND() {}

  virtual void main(int argc, char *argv[]) {
    for (int i = 0; i < argc; i++) {
      if (strcmp(argv[i], "-help") == 0) {
        fputs("Embind options (use with -embind):\n  (none yet)\n", stdout);
      }
    }
    Preprocessor_define("SWIGEMBIND 1", 0);
    allow_overloading();    /* Embind picks dispatch by arity / select_overload. */
  }

  virtual int top(Node *n) {
    String *module_name = Getattr(n, "name");
    String *outfile = Getattr(n, "outfile");
    f_out = NewFile(outfile, "w", SWIG_output_files());
    if (!f_out) { FileErrorDisplay(outfile); Exit(EXIT_FAILURE); }
    f_body   = NewString("");
    f_header = NewString("");

    /* %{ ... %} and %insert("header") -> f_header (emitted near the top).
       Other SWIG sections we don't need are null-sunk. */
    String *sink = NewString("");
    Swig_register_filebyname("header",  f_header);
    Swig_register_filebyname("runtime", sink);
    Swig_register_filebyname("wrapper", sink);
    Swig_register_filebyname("init",    sink);
    Swig_register_filebyname("begin",   sink);

    Printf(f_out, "// Generated by SWIG -embind.  Do not edit.\n\n");
    Printf(f_out, "#include <emscripten/bind.h>\n");

    Language::top(n);

    Printf(f_out, "%s\n", f_header);
    Printf(f_out, "using namespace emscripten;\n\n");
    Printf(f_out, "EMSCRIPTEN_BINDINGS(%s) {\n", module_name);
    Printf(f_out, "%s", f_body);
    Printf(f_out, "}\n");

    Delete(f_header);
    Delete(f_body);
    Delete(f_out);
    return SWIG_OK;
  }

  virtual int classHandler(Node *n) {
    String *jsname = Getattr(n, "sym:name");
    SwigType *t   = Getattr(n, "name");
    String *cname = SwigType_str(t, 0);   /* SwigType -> C++ string */
    List *bases = Getattr(n, "bases");
    String *base_part = NewString("");
    if (bases && Len(bases) > 0) {
      Node *b = Getitem(bases, 0);
      SwigType *bt = Getattr(b, "name");
      String *bcname = SwigType_str(bt, 0);
      Printf(base_part, ", emscripten::base<%s>", bcname);
      Delete(bcname);
    }
    Printf(f_body, "  emscripten::class_<%s%s>(\"%s\")\n",
           cname, base_part, jsname);
    Delete(base_part);
    current_class_cname = cname;
    ctor_arities_seen = NewHash();
    Language::classHandler(n);
    Delete(ctor_arities_seen);
    ctor_arities_seen = 0;
    current_class_cname = 0;
    Printf(f_body, "    ;\n");
    Delete(cname);
    return SWIG_OK;
  }

  virtual int memberfunctionHandler(Node *n) {
    if (!current_class_cname) return Language::memberfunctionHandler(n);
    String *jsraw = Getattr(n, "sym:name");
    String *cname = Getattr(n, "name");
    String *jsname = strip_overload_suffix(jsraw);
    String *qname  = NewStringf("%s::%s", current_class_cname, cname);
    String *target = fn_target(n, Char(qname));
    Printf(f_body, "    .function(\"%s\", %s)\n", jsname, target);
    Delete(jsname); Delete(qname); Delete(target);
    return Language::memberfunctionHandler(n);
  }

  /* SWIG appends "__SWIG_N" to sym:name for overloaded functions when
     overloading is allowed. Strip it so all overloads share the JS-facing
     name; Embind disambiguates via select_overload<Sig>(&fn). */
  String *strip_overload_suffix(String *s) {
    String *r = Copy(s);
    const char *p = strstr(Char(r), "__SWIG_");
    if (p) Delslice(r, p - Char(r), DOH_END);
    return r;
  }

  /* For overloaded fns, build the Embind cast target:
     `emscripten::select_overload<Ret(T1, T2) const?>(&qualified_name)`.
     For non-overloads, just `&qualified_name`. */
  String *fn_target(Node *n, const char *qualified_name) {
    String *out = NewString("");
    if (Getattr(n, "sym:overloaded")) {
      SwigType *rt = Getattr(n, "type");
      String *rs = rt ? SwigType_str(rt, 0) : NewString("void");
      String *tl = parm_types(Getattr(n, "parms"));
      const char *cv = "";
      String *q = Getattr(n, "qualifier");
      if (q && Strstr(q, "const")) cv = " const";
      Printf(out, "emscripten::select_overload<%s(%s)%s>(&%s)",
             rs, tl, cv, qualified_name);
      Delete(rs);
      Delete(tl);
    } else {
      Printf(out, "&%s", qualified_name);
    }
    return out;
  }

  /* Comma-separated list of C++ parameter types from a ParmList. */
  String *parm_types(ParmList *p) {
    String *out = NewString("");
    int first = 1;
    for (Parm *q = p; q; q = nextSibling(q)) {
      SwigType *t = Getattr(q, "type");
      if (!t) continue;
      String *ts = SwigType_str(t, 0);
      Printf(out, "%s%s", first ? "" : ", ", ts);
      Delete(ts);
      first = 0;
    }
    return out;
  }

  virtual int constructorHandler(Node *n) {
    if (current_class_cname && ctor_arities_seen) {
      int arity = 0;
      for (Parm *q = Getattr(n, "parms"); q; q = nextSibling(q)) ++arity;
      char keybuf[32];
      snprintf(keybuf, sizeof(keybuf), "%d", arity);

      /* Skip ctors with non-primitive parm types (any "::") unless they
         are the bound class type already declared in this binding -- that
         way we don't accidentally pick an `SX(Sparsity)` overload over
         `SX(double)` and trigger an "unbound type" runtime error.  Users
         who want such overloads can add explicit Embind factory functions
         after the auto-generated block. */
      bool skip = false;
      if (arity == 1) {
        Parm *q = Getattr(n, "parms");
        SwigType *t = Getattr(q, "type");
        String *ts = SwigType_str(t, 0);
        if (Strstr(ts, current_class_cname)) skip = true; /* copy ctor */
        else if (Strstr(ts, "::"))           skip = true; /* unbound type risk */
        Delete(ts);
      }

      if (!skip && !Getattr(ctor_arities_seen, keybuf)) {
        Setattr(ctor_arities_seen, keybuf, "1");
        String *tl = parm_types(Getattr(n, "parms"));
        Printf(f_body, "    .constructor<%s>()\n", tl);
        Delete(tl);
      }
    }
    return Language::constructorHandler(n);
  }

  virtual int globalfunctionHandler(Node *n) {
    if (current_class_cname) return Language::globalfunctionHandler(n);
    String *jsraw = Getattr(n, "sym:name");
    String *cname = Getattr(n, "name");
    String *jsname = strip_overload_suffix(jsraw);
    String *target = fn_target(n, Char(cname));
    Printf(f_body, "  emscripten::function(\"%s\", %s);\n", jsname, target);
    Delete(jsname);
    Delete(target);
    return Language::globalfunctionHandler(n);
  }

  virtual int staticmemberfunctionHandler(Node *n) {
    if (current_class_cname) {
      String *jsraw = Getattr(n, "sym:name");
      String *cname = Getattr(n, "name");
      String *jsname = strip_overload_suffix(jsraw);
      String *qname  = NewStringf("%s::%s", current_class_cname, cname);
      String *target = fn_target(n, Char(qname));
      Printf(f_body, "    .class_function(\"%s\", %s)\n", jsname, target);
      Delete(jsname); Delete(qname); Delete(target);
    }
    return Language::staticmemberfunctionHandler(n);
  }

  virtual int membervariableHandler(Node *n) {
    if (current_class_cname) {
      String *jsname = Getattr(n, "sym:name");
      String *cname  = Getattr(n, "name");
      Printf(f_body, "    .property(\"%s\", &%s::%s)\n",
             jsname, current_class_cname, cname);
    }
    return Language::membervariableHandler(n);
  }

  virtual int enumDeclaration(Node *n) {
    String *jsname = Getattr(n, "sym:name");
    String *cname  = Getattr(n, "name");
    if (!cname || Len(cname) == 0) return Language::enumDeclaration(n); // anonymous enum
    Printf(f_body, "  emscripten::enum_<%s>(\"%s\")\n", cname, jsname);
    current_enum_cname = cname;
    Language::enumDeclaration(n);
    current_enum_cname = 0;
    Printf(f_body, "    ;\n");
    return SWIG_OK;
  }

  virtual int enumvalueDeclaration(Node *n) {
    if (!current_enum_cname) return Language::enumvalueDeclaration(n);
    String *jsname = Getattr(n, "sym:name");
    String *cname  = Getattr(n, "name");
    Printf(f_body, "    .value(\"%s\", %s::%s)\n", jsname, current_enum_cname, cname);
    return Language::enumvalueDeclaration(n);
  }
};

static Language *new_swig_embind() { return new EMBIND(); }
extern "C" Language *swig_embind(void) { return new_swig_embind(); }
