# Generated by SWIG -julia. Do not edit.
module enums

const _lib = joinpath(@__DIR__, "libenums_wrap.so")

function __init__()
    ccall((:_swig_jl_init_types, _lib), Cvoid, ())
    for (n, t) in _proxy_types
        ccall((:swig_jl_register_proxy_type, _lib), Cvoid, (Cstring, Any), n, t)
    end
end

struct SwigError <: Exception
    msg::String
end
Base.showerror(io::IO, e::SwigError) = print(io, "enums error: ", e.msg)

function _check(v)
    if ccall((:swig_jl_last_error_code, _lib), Cint, ()) != 0
        throw(SwigError(unsafe_string(ccall((:swig_jl_last_error_msg, _lib), Cstring, ()))))
    end
    v
end

function _takestr(p::Ptr{UInt8})
    _check(p)
    s = unsafe_string(p)
    ccall((:swig_jl_str_free, _lib), Cvoid, (Ptr{UInt8},), p)
    s
end

mutable struct Foo
    ptr::Ptr{Cvoid}
    function Foo(p::Ptr{Cvoid})
        x = new(p)
        finalizer(o -> (ccall((:_swig_Foo_delete, _lib), Cvoid, (Ptr{Cvoid},), o.ptr); o.ptr = C_NULL), x)
        x
    end
end
mutable struct iFoo
    ptr::Ptr{Cvoid}
    function iFoo(p::Ptr{Cvoid})
        x = new(p)
        finalizer(o -> (ccall((:_swig_iFoo_delete, _lib), Cvoid, (Ptr{Cvoid},), o.ptr); o.ptr = C_NULL), x)
        x
    end
end

const _proxy_types = [
    ("Foo", Foo),
    ("iFoo", iFoo),
]

@enum foo1::Cint foo1_CSP_ITERATION_FWD=0 foo1_CSP_ITERATION_BWD=11 
const CSP_ITERATION_FWD = Int(ccall((:_swig_const_CSP_ITERATION_FWD, _lib), Clonglong, ()))
const CSP_ITERATION_BWD = Int(ccall((:_swig_const_CSP_ITERATION_BWD, _lib), Clonglong, ()))
@enum foo3::Cint foo3_ABCDE=0 foo3_FGHJI=1 
const ABCDE = Int(ccall((:_swig_const_ABCDE, _lib), Clonglong, ()))
const FGHJI = Int(ccall((:_swig_const_FGHJI, _lib), Clonglong, ()))
# skipped bar1 (parameter type)
# skipped bar2 (parameter type)
# skipped bar3 (parameter type)
@enum sad::Cint sad_boo=0 sad_hoo=5 
const boo = Int(ccall((:_swig_const_boo, _lib), Clonglong, ()))
const hoo = Int(ccall((:_swig_const_hoo, _lib), Clonglong, ()))
const globalinstance1 = Int(ccall((:_swig_const_globalinstance1, _lib), Clonglong, ()))
const globalinstance2 = Int(ccall((:_swig_const_globalinstance2, _lib), Clonglong, ()))
const globalinstance3 = Int(ccall((:_swig_const_globalinstance3, _lib), Clonglong, ()))
const AnonEnum1 = Int(ccall((:_swig_const_AnonEnum1, _lib), Clonglong, ()))
const AnonEnum2 = Int(ccall((:_swig_const_AnonEnum2, _lib), Clonglong, ()))
const Foo_BAR1 = Int(ccall((:_swig_const_Foo_BAR1, _lib), Clonglong, ()))
const Foo_BAR2 = Int(ccall((:_swig_const_Foo_BAR2, _lib), Clonglong, ()))
const iFoo_Phoo = Int(ccall((:_swig_const_iFoo_Phoo, _lib), Clonglong, ()))
@enum Exclamation::Cint Exclamation_goodness=0 Exclamation_gracious=1 Exclamation_me=2 
const goodness = Int(ccall((:_swig_const_goodness, _lib), Clonglong, ()))
const gracious = Int(ccall((:_swig_const_gracious, _lib), Clonglong, ()))
const me = Int(ccall((:_swig_const_me, _lib), Clonglong, ()))
@enum ContainYourself::Cint ContainYourself_slap=10 ContainYourself_mine=11 ContainYourself_thigh=12 
const slap = Int(ccall((:_swig_const_slap, _lib), Clonglong, ()))
const mine = Int(ccall((:_swig_const_mine, _lib), Clonglong, ()))
const thigh = Int(ccall((:_swig_const_thigh, _lib), Clonglong, ()))
Foo() = Foo(_check(ccall((:_swig_Foo_new_Foo__SWIG_0, _lib), Ptr{Cvoid}, (), )))
iFoo() = iFoo(_check(ccall((:_swig_iFoo_new_iFoo__SWIG_0, _lib), Ptr{Cvoid}, (), )))
export foo1_CSP_ITERATION_FWD, foo1_CSP_ITERATION_BWD, foo1, CSP_ITERATION_FWD, CSP_ITERATION_BWD, foo3_ABCDE, foo3_FGHJI, foo3, ABCDE, FGHJI, sad_boo, sad_hoo, sad, boo, hoo, globalinstance1, globalinstance2, globalinstance3, AnonEnum1, AnonEnum2, Foo, Foo_BAR1, Foo_BAR2, iFoo, iFoo_Phoo, Exclamation_goodness, Exclamation_gracious, Exclamation_me, Exclamation, goodness, gracious, me, ContainYourself_slap, ContainYourself_mine, ContainYourself_thigh, ContainYourself, slap, mine, thigh

end # module enums
